apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-homolog
spec:
  acme:
    server: # url API que certifica - lets encrypt - https://letsencrypt.org/
    email: # email de dominio
    privateKeySecretRef:
      name: letsencrypt-homolog
    solvers:
    - http01:
        ingress:
          class: nginx

---

# SEGURO PROD

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: # url API que certifica - lets encrypt - https://letsencrypt.org/
    email: # email de dominio
    privateKeySecretRef:
      name: letsencrypt-homolog
    solvers:
    - http01:
        ingress:
          class: nginx
