apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 20
  selector:
    matchLabels:
      versao: v1
  template:
    metadata:
      labels:
        versao: v1
    spec:
      containers:
      - name: stess-test-container-v1
        image: bpvcode/stresss-test:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
