apiVersion: v1
kind: Pod
metadata:
  name: stress-test-pod-latest
  labels:
    app: stresss-test-latest
    versao: latest
spec:
  containers:
    - name: stess-test-container-latest
      image: bpvcode/stresss-test:latest