FROM golang:1.16-alpine3.13 as build

WORKDIR /build

COPY . .

#Comando de build da aplicação go - irá gerar um ficheiro executável `main`
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

#  New stagee
FROM alpine:3.14

WORKDIR /app

# Copiar do Stage a cima "as build" na localização `build/main` (ficheiro executável `main` criado a cima), para este workdir em `/app`
COPY --from=build /build/main .

#Executar o ficheiro executável
CMD ["./main"]