FROM ubuntu

RUN apt-get update && apt-get install --yes curl

# Run this in container terminal, after create and execute the image:
# curl https://www.google.com
# Ex: root@3b55c84f0aaf:/# curl https://www.google.com